apiVersion: v1
kind: ConfigMap
metadata:
  name: settlement-api-config
  namespace: payments-production
  labels:
    app.kubernetes.io/name: settlement-api
    app.kubernetes.io/part-of: payments-platform
data:
  application-production.yml: |
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 25s
    server:
      shutdown: graceful
    logging:
      level:
        root: INFO
        com.northstar.payments: INFO
    management:
      endpoint:
        health:
          show-details: never
