apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-config
  namespace: commerce-production
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/part-of: commerce-platform
data:
  application-production.properties: |
    inventory.default-warehouse=eu-west-1
    logging.level.com.northstar.commerce.inventory=INFO
    management.endpoint.health.show-details=never
