apiVersion: v1
kind: Secret
metadata:
  name: inventory-service-runtime
  namespace: commerce-production
  labels:
    app.kubernetes.io/name: inventory-service
type: Opaque
stringData:
  INVENTORY_PARTNER_AUDIENCE: inventory.partner.northstar.internal
